# Generated by Django 5.2.5 on 2026-01-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_app_userappmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, help_text='App icon/image', null=True, upload_to='apps/'),
        ),
    ]
