# Generated by Django 5.2.5 on 2025-08-24 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmcb_form_data', models.JSONField(blank=True, null=True)),
                ('meta_campaign_dates', models.CharField(blank=True, max_length=255)),
                ('meta_video_image', models.CharField(blank=True, max_length=255)),
                ('meta_main_copy_options', models.JSONField(blank=True, null=True)),
                ('meta_headline', models.TextField(blank=True)),
                ('meta_desktop_display_copy', models.TextField(blank=True)),
                ('meta_website_url', models.URLField(blank=True, max_length=500)),
                ('meta_call_to_action', models.CharField(blank=True, max_length=255)),
                ('google_campaign_dates', models.CharField(blank=True, max_length=255)),
                ('google_creative', models.CharField(blank=True, max_length=255)),
                ('google_headlines', models.JSONField(blank=True, null=True)),
                ('google_long_headline', models.TextField(blank=True)),
                ('google_descriptions', models.JSONField(blank=True, null=True)),
                ('google_website_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('dms_sync_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='property_app.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='property_app.property'),
        ),
        migrations.CreateModel(
            name='PropertyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_seasonal_campaign_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creative_charges_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meta_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meta_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('display_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('display_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='property_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property_app.propertygroup'),
        ),
    ]
