# Generated by Django 5.2.5 on 2025-08-30 05:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='property_logos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, numbers, and hyphens are allowed.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AddField(
            model_name='property',
            name='theme',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserPropertyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('property_admin', 'Property Admin'), ('group_admin', 'Group Admin')], default='tenant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='property_app.property')),
                ('property_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='property_app.propertygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'property', 'property_group'), name='unique_user_property_group_membership')],
            },
        ),
    ]
