# Generated by Django 5.2.5 on 2025-10-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='google_long_headline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_headline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
