# Generated by Django 5.2.5 on 2025-10-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_campaign_google_long_headline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('meta_ad_copywriter', 'Meta Ad Copywriter'), ('google_ads_copywriter', 'Google Ads Copywriter'), ('budget_extraction', 'Budget Extraction'), ('custom', 'Custom')], help_text='Type of configuration/prompt', max_length=30)),
                ('name', models.CharField(help_text='Human-readable name for this configuration', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this configuration is used for')),
                ('system_prompt', models.TextField(help_text='The system prompt template. Use {variable_name} for variable substitution.')),
                ('user_prompt_template', models.TextField(blank=True, help_text='The user prompt template. Use {variable_name} for variable substitution.')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text="List of available variables for substitution in the format [{'name': 'variable_name', 'description': 'What this variable represents'}]")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default configuration for this type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configurations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text="If set, this configuration is specific to this property. If null, it's a global configuration.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='property_app.property')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['config_type', 'property__name', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('config_type', 'property', 'is_default'), name='unique_default_per_type_property')],
            },
        ),
    ]
