# Generated by Django 5.2.5 on 2025-10-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_campaign_google_long_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name for the platform', max_length=100)),
                ('net_rate', models.DecimalField(decimal_places=4, default=0.85, help_text='Rate to calculate net from gross (e.g., 0.8500 for 85% net rate)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='campaignbudget',
            name='display_gross',
        ),
        migrations.RemoveField(
            model_name='campaignbudget',
            name='display_net',
        ),
        migrations.RemoveField(
            model_name='campaignbudget',
            name='meta_gross',
        ),
        migrations.RemoveField(
            model_name='campaignbudget',
            name='meta_net',
        ),
        migrations.CreateModel(
            name='PlatformBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Gross budget amount entered by Super User', max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Net amount calculated from gross (read-only field)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_budgets', to='property_app.campaignbudget')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='property_app.platform')),
            ],
            options={
                'verbose_name': 'Platform Budget',
                'verbose_name_plural': 'Platform Budgets',
                'unique_together': {('campaign_budget', 'platform')},
            },
        ),
    ]
