# Generated by Django 5.2.5 on 2025-10-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_flexible_campaign_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('meta_ad', 'Meta Ad Content'), ('google_display', 'Google Display Content')], help_text='Type of prompt (Meta or Google)', max_length=100)),
                ('system_message', models.TextField(help_text="System message that defines the AI's role and behavior")),
                ('user_prompt_template', models.TextField(help_text='User prompt template with variables in {curly_braces}')),
                ('available_variables', models.JSONField(default=dict, help_text='Dictionary of available variables with descriptions')),
                ('is_active', models.BooleanField(default=True, help_text='Only active prompts are used for content generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Leave empty for default prompt, or select property for custom prompt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_configurations', to='property_app.property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Configuration',
                'verbose_name_plural': 'Prompt Configurations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('prompt_type', 'property'), name='unique_prompt_per_property_type')],
            },
        ),
    ]
