# Generated by Django 5.2.5 on 2025-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='config_type',
            field=models.CharField(choices=[('meta_ad_copywriter', 'Meta Ad Copywriter'), ('google_ads_copywriter', 'Google Ads Copywriter'), ('custom', 'Custom')], help_text='Type of configuration/prompt', max_length=30),
        ),
    ]
