# Generated by Django 5.2.5 on 2025-11-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_clientnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='google_website_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_website_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
