# Generated by Django 5.2.5 on 2025-08-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_creativeasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='google_creative',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='meta_video_image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='notes',
        ),
        migrations.AddField(
            model_name='campaign',
            name='center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_assets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_ready',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_assets',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_ready',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='google_campaign_dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='google_long_headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='google_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_call_to_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_campaign_dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_desktop_display_copy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='meta_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CampaignBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_charges_deductions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_gross', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('meta_gross', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('meta_net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('display_gross', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('display_net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='property_app.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyBudget',
        ),
    ]
