# Generated by Django 5.2.5 on 2025-09-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0005_remove_campaign_google_creative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='google_assets',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='google_campaign_dates',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='meta_assets',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='meta_campaign_dates',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativeasset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeasset',
            name='platform_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CampaignDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_type', models.CharField(choices=[('event', 'Event Date'), ('milestone', 'Milestone'), ('deadline', 'Deadline'), ('promotion', 'Promotion Date')], default='event', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_dates', to='property_app.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Date',
                'verbose_name_plural': 'Campaign Dates',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
