# Generated by Django 5.2.5 on 2025-09-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_remove_campaign_google_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
