# Generated by Django 5.2.5 on 2025-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0007_campaign_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, help_text='When AI processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_processing_error',
            field=models.TextField(blank=True, help_text='Error message if AI processing failed', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of AI content generation for this campaign', max_length=20),
        ),
    ]
