# Generated by Django 5.2.5 on 2025-09-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0008_campaign_ai_processed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='approved_by_client',
        ),
        migrations.AddField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admin_approved', 'Admin Approved'), ('client_approved', 'Client Approved'), ('fully_approved', 'Fully Approved')], default='pending', help_text='Current approval status of the campaign', max_length=20),
        ),
    ]
