# Generated by Django 5.2.5 on 2025-09-27 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0009_remove_campaign_approved_by_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Notification', 'verbose_name_plural': 'Client Notifications'},
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('campaign_update', 'Campaign Update'), ('approval', 'Approval')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CampaignComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='property_app.campaign')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='property_app.campaigncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Comment',
                'verbose_name_plural': 'Campaign Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='property_app.campaigncomment'),
        ),
    ]
